#!/usr/bin/env node

var generator = require("../metalsmith.js")

generator.build(function(error) {
  if (error) {
    console.log("Error: ", error)
  } else {
    console.log("Site generated.")
  }
})
